### ISSUE TITLE
Problem with some workshops

### ISSUE THREAD

**Issue by aikoncwd** [DFgraphics/Phoebus#10]
I don't know why, but the **Phoebus/SpaceFox** is showing some workshops different in the actual version (LNP 0.44.02-r4), this is how *still* looks:

![ugly](https://imgur.com/Zjhp3pT.png)

On the last version (LNP 0.43.05-r11), the *still* workshop looks like this:

![nice](https://imgur.com/EmjZQPw.png)

Is there any way to revert those changes and get the pretty workshops again?

**Comment by lethosor** [comment]
Are you using TWBT?

**Comment by jecowa** [comment]
I agree that it looks like like Text Will Be Text (TWBT) is disabled.

It looks like version 0.44.02-r4 of PE's starter pack has TWBT and DFHack both enabled by default.

Did you maybe turn DFHack off in the DFHack tab of the launcher? Or did you switch your Print Mode to something other than "TWBT".

The [last change made to the overrides](https://github.com/DFgraphics/Phoebus/pull/9/commits/0d52d8e0cc387f3a5a7576379e12afadb8dbd970) was 20 days ago to adjust the Minecart/Wheelbarrow. And there haven't been any changes before that since 2016 in January.

**Comment by aikoncwd** [comment]
@lethosor @jecowa Im using DFHack + TWBT, since Im playing with `multilevel 5` eanbled. A frind reported me the same issue, so I'm not the only one (he is using spacefox, im using phoebus). Can you guys test PE's 0.44.02-r4?

**Comment by aikoncwd** [comment]
Maybe its not a problem of the tileset, maybe there was an error when @PeridexisErrant packed 0.44.02-r4, hope he can read this! :)

**Comment by jecowa** [comment]
I'm having the issue on Mac too. Even with the same overrides png files and the same overrides text file, different overrides graphics are being used for my carpentry shop with Phoebus on DF v0.43.05 than on DF v0.44.02. The rest of it may be uglier, but I like that the v0.44 version is using a table with a saw override graphic for my carpentry shop instead of the bookshelf override that gets used in v0.43. It's using override tile 105 in v0.44 while it uses override tile 113 in v0.43. From the overrides text file, it looks like it's supposed to be using overrides tile 113. 
They both look the same in ascii graphics packs, so Toady didn't change the look of them.

**Comment by aikoncwd** [comment]
Maybe its an error with TwbT plugin? I will PM @mifki ...

**Comment by jecowa** [comment]
At least in Phoebus, in DF v0.44.02, the Carpentry shop seems to be using the overrides.txt data for the Craftsdwarf shop.

**Comment by carterscottm** [comment]
This is happening in linux as well. Other tiles are also affected, such as slabs, coffins, and planted farm plots. However, minecarts now look like proper minecarts instead of using the same tile as wheelbarrows.

**Comment by pronvit** [comment]
This is a problem in DFHack, building IDs list has changed in 0.44 but hasn't been updated in DFHack. Nothing you can do now unfortunately.

**Comment by aikoncwd** [comment]
Thanks for appointing that @pronvit , is there any admin of DFHack here? @lethosor ? 😺

**Comment by lethosor** [comment]
Should be fixed in the next DFHack release.

**Comment by aikoncwd** [comment]
We can close this. Thanks! :D

**Comment by Eddyskingdom** [comment]
the bug is back again in virsion 44.09 in LNP work

**Comment by lethosor** [comment]
What specific pack are you using, and what TWBT version?

**Comment by Eddyskingdom** [comment]
Phoebus+TWBT i hade it  turnd off two to see if it was the same but the bug was still ter

**Comment by lethosor** [comment]
* What "LNP" are you using? (Link)
* What is the **version number** of TWBT? It should be logged in the DFHack console.

**Comment by Eddyskingdom** [comment]
http://dffd.bay12games.com/file.php?id=7622
and TWBT 6.41
and i have tried dis on other packts like ironhand and spacefox but still the same

**Comment by lethosor** [comment]
So what exactly is the issue in your case? Are workshops displaying as other workshops? Or do they just not look right? Can you provide a screenshot?

**Comment by Eddyskingdom** [comment]
![image](https://user-images.githubusercontent.com/25956554/39544845-a8bc8d80-4e4f-11e8-80cf-c2f580ef07a9.png)

**Comment by Eddyskingdom** [comment]
ter all the workshops plus furnaces but i still dont understand why dis is happening it must just work right?

**Comment by lethosor** [comment]
I don't use Phoebus so I'm still not sure what the issue is.

In #15 you said something about tables. Are tables missing or something?

Are these workshops completely built?

**Comment by Eddyskingdom** [comment]
yes ter completly build and normaly ter are tabels in the workshop so they look like work tabels
that is what the bolbs are in the screen shot but some opjects are missing
but for me it looks like that ironhand and phoebus mixt

**Comment by lethosor** [comment]
Are you sure they're all supposed to have tables? Not all types of workshops do.

Also, I don't think your problem is the same as the one in this report, so #15 is probably a better place to discuss it.

**Comment by Eddyskingdom** [comment]
ok

and yes not all types work shops do have only tabels some have bookcase or other things like a loom
